config/routes.rb
ScHydraHead::Application.routes.draw do
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users

   root 'welcome#index'

  get "welcome/about"
  get "welcome/contact_us"
  get "welcome/off_campus_login"
  get "welcome/login_link"
  get "welcome/content"
  post "welcome/content"

  get "catalog/email"
  post "catalog/email1"

  get "ingest/ingest"
  post "ingest/ingestFile"
  get "etds/show"
  

  resources :etds
  post "etds/edit"
  post "etds/show"
  
  resources :delete
  post "delete/delete_confirm"

  get "search/search"

  get "ucsb/ucsb_form1"
  post "ucsb/ucsb_form"
  get "ucsb/ucsb_emailf"
  post "ucsb/ucsb_email"

  

end

app/views/shared/_footer.html.erb
<% url = APP_CONFIG['rails_url'] %>
<div id="page_footer">
	<div id="footer">
		<p>
		<!-- <a href="/catalog"><b>Search & Research</b></a> | -->
		<!-- <a href="/">Help</a> | --><a href="/welcome/about">About ADRL</a> |
		<!--a href="/welcome/contact_us">Contact Us</a-->
		<a href="/ucsb/ucsb_form1">Contact Us</a> </p>
		<div class="copyright">
			Copyright &copy; 2014 The Regents of the University of California, All Rights 
			Reserved. </div>
		<!-- div copyright ends -->
		
		<div id="footer_logo">

			<!-- div footer_brand_updated ends -->
			<div id="footer_right">
				<div class="footer_right_updated">
					<a href="http://www.library.ucsb.edu">
					<!--img alt="Adrl logo 363x84" src="/assets/blacklight/ADRL_Footer_LogoBlock.png"></a-->
					<img alt="Adrl logo 363x84" src="/assets/blacklight/library-logo.png"></a>
				</div>	<!-- div footer_right_updated ends -->

				<div class="footer_right_bottom">
					<a href="http://www.ucsb.edu">
					<img alt="UCSB logo" src="/assets/blacklight/UCSB-footer-logo.png"></a>
				</div>	<!-- div footer_right_bottom ends -->

			<!-- div footer_right ends --></div>
		<!-- div footer_logo ends --></div>
	<!-- div footer ends --></div>
<!-- div page_footer ends --></div>

app/views/shared/_header_navbar.html.erb
<% url = APP_CONFIG['rails_url'] %>
<% on_campus = session[:on_campus] %>


<div class="page-header">
<div id="header-navbar-fixed-top" class="navbar navbar-fixed-top">
	<div class="navbar-inner">
            <div class="container">
              <div class="row">
                      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </a>

<div class="span3header">
						<!--	    <%= link_to '', root_path, :class => "brand" %>-->
						<!--<a  href="./Alexandria%20Digital%20Research%20Library_files/Alexandria%20Digital%20Research%20Library.htm">-->
						<a href="/"><img alt="Adrl logo 363x84" src="/assets/blacklight/ADRL_Logo_363x84.png" width="60%"></a>
						<!--</a>--></div>
					<div class="util-links-otherupdate">
						<% if render_bookmarks_control? %><%= link_to t('blacklight.header_links.bookmarks'), bookmarks_path %>
						<% end %>
						<!-- &nbsp; | &nbsp; -->&nbsp;&nbsp;&nbsp; <%= link_to t('blacklight.header_links.search_history'), search_history_path %>
						<% if has_user_authentication_provider? and current_user %>
						<!-- &nbsp; | &nbsp; -->&nbsp;&nbsp;&nbsp; <%#= link_to t('blacklight.header_links.saved_searches'), saved_searches_path %>
						<% end %>
					</div>

					<% if has_user_authentication_provider? %>
						<div class="util-links-loginupdate">
							<!--a href="./users/sign_in">Off-Campus Login</a-->
<!--							      <% if current_user %>
							        &nbsp;&nbsp;
							        <%#= link_to t('blacklight.header_links.logout'), destroy_user_session_path %>
							        <span class = "user_logged" >
							          <%#= "[#{ link_to current_user, edit_user_registration_path }]".html_safe unless current_user.to_s.blank? %>
							        </span>
							      <% else %>
							        <%#= link_to t('blacklight.header_links.login'), new_user_session_path %>
							      <% end %> -->


<!--div class="util-links-login off-campus-login-link"-->
        <ul class="nav navbar-nav navbar-right">
                <li id="menu2" class="dropdown1" style="left: 23px; top: 0px; width: 186px">
                <div class="dropdown dropdown-login">
                    <% if(on_campus) %>
                        <p style="color: white;"> Logged In<p>
                    <% else %>
                        <!--a class="dropdown-toggle RightLink" data-toggle="dropdown" href="welcome/off_campus_login">Off-Campus Login </a-->
                        <a class="dropdown-toggle RightLink" data-toggle="dropdown" href="<%= url %>welcome/off_campus_login">Off-Campus Login </a>
                    <% end %>
                </div>
                <div class="dropdown-menu dropdown-login-menu">
                   <div class="login-main">
                        <div class="login-text">
                                <h2>Off-Campus Login</h2>
                                <p>Bibliographic records of all materials in the Alexandria Digital
                                Research Library are accessible to the public. Due to copyright
                                and other access restrictions, some items are only available to
                                UCSB faculty, students, and staff. When accessing the site from
                                off-campus, UCSB users should login using a UCSB NetID and password
                                to view items restricted to the University community. </p>
                        </div>
                        <div class="login-margin">&nbsp;</div>
                        <div class="off-campus-wrapper">
                        <!--form id="offcampus-login-form" action="http://proxy.library.ucsb.edu:2048/login?url=http://alexandria.ucsb.edu/" method="post"-->

                        <% login_url = "http://proxy.library.ucsb.edu:2048/login?url=" + url %>
                        <%# login_url = "http://proxy.library.ucsb.edu:2048/login?url=http://alexandria.ucsb.edu/" %>
                        <form id="offcampus-login-form" action=<%= login_url %> method="post">
                                <div class="login-form">
                                <br>
                                        <div class="login-form-content">
                                                <label class="label-username" for="username">UCSB NetID</label>
                                                <input class="input-username" id="username" name="user" tabindex="4" title="UCSB NetID" type="text" value=""/>
                                                <label class="label-password" for="password">Password</label>
                                                <input class="input-password" id="password" name="pass" tabindex="5" title="password" type="password" value=""/>
                                                <input class="login-button" tabindex="6" type="submit" value="Login" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                                <a href="https://secure.identity.ucsb.edu/manager/">Forgot your login?</a>
                                        </div>
                                </div>
                        </form>
                        </div> <!-- off-campus-wrapper ends here -->
                   </div> <!-- login_main ends here -->
                </div>
                </li>
        </ul>
<!--/div-->




						</div> <!-- div util-links-loginupdate ends -->
					<% end %>
				</div>

				<div id="searchbarupdate" class="span6 clearfix">
					<%= render_search_bar  %></div>
				<!--<div class="span3 nav-collapse">
					<%#= render :partial=>'/user_util_links' %>
				</div>-->
			</div>
		</div>
	</div>
</div>