config/routes.rb
ScHydraHead::Application.routes.draw do
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users

   root 'welcome#index'

  get "welcome/about"
  get "welcome/contact_us"
  get "welcome/off_campus_login"
  get "welcome/login_link"
  get "welcome/content"
  post "welcome/content"

  get "catalog/email"
  post "catalog/email1"

  get "ingest/ingest"
  post "ingest/ingestFile"
  get "etds/show"
  

  resources :etds
  post "etds/edit"
  post "etds/show"
  
  resources :delete
  post "delete/delete_confirm"

  get "search/search"

  get "ucsb/ucsb_form1"
  post "ucsb/ucsb_form"
  get "ucsb/ucsb_emailf"
  post "ucsb/ucsb_email"

  

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'
#require './app/models/solr_service.rb'

class CatalogController < ApplicationController

  include Blacklight::Catalog
  include Hydra::Controller::ControllerBehavior
  include BlacklightAdvancedSearch::ParseBasicQ
  include Blacklight::SolrHelper

  #helper_method :find_client_ip

  # These before_filters apply the hydra access controls
  #before_filter :enforce_show_permissions, :only=>[:show]
  # This applies appropriate access controls to all solr queries
  CatalogController.solr_search_params_logic += [:add_access_controls_to_solr_params]
  # This filters out objects that you want to exclude from search results, like FileAssets
  CatalogController.solr_search_params_logic += [:exclude_unwanted_models]


  configure_blacklight do |config|
    config.default_solr_params = {
      :qt => 'search',	
      :rows => 10
      #:q => '*.*' 
      #("hl.fl").to_sym => "title",
      #("hl.simple.pre").to_sym => '<span class="label label-info">',
      #("hl.simple.post").to_sym => "</span>",
      #:hl => true
    }

    config.default_document_solr_params = {
      #("hl.fl").to_sym => "title",
      #("hl.simple.pre").to_sym => '<span class="label label-info">',
      #("hl.simple.post").to_sym => "</span>",
      #:hl => true
    }

    # solr field configuration for search results/index views
    config.index.show_link = 'title_tesim'
    config.index.record_display_type = 'has_model_ssim'

    # solr field configuration for document/show views
    config.show.html_title = 'title_tesim'
    config.show.heading = 'title_tesim'
    config.show.display_type = 'has_model_ssim'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _tsimed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field solr_name('object_type', :facetable), :label => 'Format'
    config.add_facet_field solr_name('person_full_name_cid_facet', :facetable), :label => 'Names'
#    config.add_facet_field solr_name('origin_info_date_issued', :facetable), :label => 'Publication Year'
#    config.add_facet_field solr_name('subject_topic', :facetable), :label => 'Topic', :limit => 20
#    config.add_facet_field solr_name('origin_info_place_text', :facetable), :label => 'Locations'
#    config.add_facet_field solr_name('title', :facetable), :label => 'Title', :limit => 20

    config.add_facet_field solr_name('person', :facetable), :label => 'Author/Contributor', :limit => 20
    #config.add_facet_field solr_name('person', :facetable), :label => 'Author/Contributor', :limit => 20, :helper_method => :genre_format_helper
    #config.add_facet_field solr_name('person_namePart', :facetable), :label => 'Author_name_split', :limit => 20
    #config.add_facet_field solr_name(:field_name => ('names_family_name','names_given_name'), :facetable, :label => 'Author_name_split', :limit => 20)
    
    #config[:facet] = {
#    config.add_facet_field solr_name{
#	:field_names => (facet_fields = ["names_family_name", "names_given_name"]),:label => "Author_name_split",:limits => 20}

#    config.add_facet_field solr_name('personal_full_name', :facetable), :label => 'Author_full_name', :limit => 20
#    config.add_facet_field solr_name('names', :facetable), :label => 'Personal_names', :limit => 20
#    config.add_facet_field solr_name('personal_names', :facetable), :label => 'Author/Contributor', :limit => 20

    config.add_facet_field solr_name('corporate_names', :facetable), :label => 'Department', :limit => 20
    #config.add_facet_field solr_name('corporate_names', :facetable), :label => 'Department', :limit => 20, :separator => '<br/>'
    #config.add_facet_field solr_name('organization', :facetable), :label => 'Department', :limit => 20
    config.add_facet_field solr_name('genre', :facetable), :label => 'Genre', :limit => 20
    config.add_facet_field solr_name('create_key_date', :facetable), :label => 'Date', :limit => 20
    #config.add_facet_field solr_name('origin_info_date', :facetable), :label => 'Dates', :limit => 20
    config.add_facet_field solr_name('language_lang_code', :facetable), :label => 'Language', :limit => 20
    config.add_facet_field solr_name('ext_degree_level', :facetable), :label => 'Degree Level', :limit => 20
    #config.add_facet_field solr_name('ext_degree_discipline', :facetable), :label => 'Discipline', :limit => true
    config.add_facet_field solr_name('ext_degree_discipline', :facetable), :label => 'Discipline', :limit => 20

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys


    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    #config.add_index_field solr_name('ark', :stored_searchable, type: :string), :label => 'ARK:'
    #config.add_index_field solr_name('title', :stored_searchable, type: :string), :label => 'Title:'
    # commented for highlight changes
    #config.add_index_field solr_name('title', :stored_searchable, type: :string), :label => 'Title:', :highlight => true
    config.add_index_field solr_name('author_part', :stored_searchable, type: :string), :label => 'Author:'

    config.add_index_field solr_name('origin_info', :stored_searchable, type: :string), :label => 'Published:', :helper_method => :published_format_helper
    #config.add_index_field solr_name('origin_info_publisher', :stored_searchable, type: :string), :label => 'Published:'
    #config.add_index_field solr_name('origin_info_place_text', :stored_searchable, type: :string), solr_name('origin_info_publisher', :stored_searchable, type: :string), :label => 'Published:'
    #config.add_index_field solr_name('origin_info_place_text' + ':' + 'origin_info_publisher', :stored_searchable, type: :string), :label => 'Published:'
    #config.add_index_field solr_name('origin_info_publisher'+':', :stored_searchable, type: :string), :label => 'Published:'

    #config.add_index_field solr_name('origin_info_date_issued_enc', :stored_searchable, type: :string), :label => 'Year:' 
    #config.add_index_field solr_name('date_created_key', :stored_searchable, type: :string), :label => 'Date Created:' 
    config.add_index_field solr_name('create_key_date', :stored_searchable, type: :string), :label => 'Date Created:' 
    #config.add_index_field solr_name('isbn', :stored_searchable, type: :string), :label => 'ISBN:'
    config.add_index_field solr_name('object_type', :stored_searchable, type: :string), :label => 'Format:'


    # Highlight
    #config.add_index_field 'ark', :highlight => true
    #config.add_facet_field solr_name('object_type', :facetable), :label => 'Format', :show => false
    #config.add_field_configuration_to_solr_request!

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    #config.add_show_field solr_name('title', :stored_searchable, type: :string), :label => 'Title:'
    # commented for highlight changes
    #config.add_show_field solr_name('title', :stored_searchable, type: :string), :label => 'Title:', :highlight => true
    config.add_show_field solr_name('author_part', :stored_searchable, type: :string), :label => 'Author:'
    config.add_show_field solr_name('origin_info', :stored_searchable, type: :string), :label => 'Published:', :helper_method => :published_format_helper
    #config.add_show_field solr_name('origin_info_date_issued_enc', :stored_searchable, type: :string), :label => 'Year:'
    config.add_show_field solr_name('create_key_date', :stored_searchable, type: :string), :label => 'Date Created:'
    config.add_show_field solr_name('object_type', :stored_searchable, type: :string), :label => 'Format:'
    config.add_show_field solr_name('extent', :stored_searchable, type: :string), :label => 'Description:'

    #config.add_show_field solr_name('note_advisor', :stored_searchable, type: :string), :label => 'Notes:'
    config.add_show_field solr_name('note_advisor', :stored_searchable, type: :string), :label => 'Notes:', :helper_method => :note_format_helper

    config.add_show_field solr_name('note_thesis', :stored_searchable, type: :string), :label => 'Dissertation:'
    config.add_show_field solr_name('note_bibliography', :stored_searchable, type: :string), :label => 'Bibliography:'
    config.add_show_field solr_name('abstract', :stored_searchable, type: :string), :label => 'Summary:'

app/helpers/catalog_helper.rb
require 'date'

module CatalogHelper
  include Blacklight::CatalogHelperBehavior

  def find_client_ip
    @req_ip = request.remote_ip
    #@rem_ips = @env['HTTP_X_FORWARDED_FOR']
    @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
  end

  def check_on_campus
    on_campus = session[:on_campus]
    if (on_campus.nil?)
      session[:on_campus] = false
      @req_ip = request.remote_ip
      #@rem_ips = @env['HTTP_X_FORWARDED_FOR']
      @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
      if (@req_ip.start_with?("128.111") || @req_ip.start_with?("169.231"))
        @session_ip = @req_ip
        session[:on_campus] = true
      end
    end
  end

  # this method loads the hashmap of icons path based on the fedora mime-types
  def load_file_icons
    @icons_hash = {}
    CSV.foreach('config/file_icons_mappings.csv') do |row|
      @icons_hash[row[0]] = row[1]
    end
    @icons_hash
  end

  # this method loads the hashmap of extensions based on the fedora mime-types
  def load_file_extensions
    @ext_hash = {}
    CSV.foreach('config/extension_mappings.csv') do |row|
      @ext_hash[row[0]] = row[1]
    end
    @ext_hash
  end

  # format date to display for embargoed etds message
  def format_embargoed_date(embargo_date)
    date = DateTime.parse(embargo_date.to_s)
    formatted_date = date.strftime("%B %d, %Y")
    return formatted_date
  end

end

app/views/catalog/_document.html.erb
    <% # container for a single doc -%>
    <div class="document <%= render_document_class document %>">
      <%= render :partial => 'document_header', :locals => { :document => document, :document_counter => document_counter } %>

      <%= render_document_partial document, :thumbnail, :document_counter => document_counter %>

      <% # container for static thumbnail image partial view -%>
      <%#= render :partial => 'document_static_thumbnail', :locals => { :document => document, :document_counter => document_counter } %>

        <% # bookmark functions for items/docs -%>
        <%#= render_index_doc_actions document, :wrapping_class => "documentFunctions span2" %>
        <%#= render :partial => 'catalog/bookmark_control', :locals => {:document=> document} %>

      <% # main container for doc partial view -%>
      <%= render_document_partial document, :index, :document_counter => document_counter %>

      <!--div class="documentHeader clearfix"-->
      <div class="clearfix">
        <%#= render :partial => 'catalog/bookmark_control', :locals => {:document=> document}.merge(:wrapping_class => "documentFunctions span2") %>
        <%#= render_index_doc_actions document, :wrapping_class => "documentFunctions span2" %>
      </div>

    </div>

app/views/catalog/_document_static_thumbnail.html.erb
<% url = APP_CONFIG['rails_url'] %>
<% fedora_url = APP_CONFIG['fedora_url'] %>
     
      <% # static thumbnail image for doc items in index view -%>
      <div class="document-thumbnail">
        
        <%- # static thumbnail container for doc partial view -%>
         <% counter = document_counter_with_offset(document_counter) %>
         <%#= link_to_document document, :label => image_tag("blacklight/pdf_icon.jpg"), :counter => counter %>

	 <%- pid = document["id"] -%>
	 <%- e = ETD.find(pid) -%>
         <%- embargo = e.rightsMetadata.embargo_release_date -%>
	 <%- on_campus = session[:on_campus] %>
	 <%- link = fedora_url + '/fedora/objects/' + pid + '/datastreams/dataContent/content' -%>

	 <% if (!current_user.nil?) %>
	   <% if (current_user.groups.include?("community") && embargo.nil? ) || (current_user.groups.include?("admin") || current_user.groups.include?("staff")) %>
	     <%= link_to link, :title => "PDF_Link", :target => "_blank" do %>
               <%= image_tag("blacklight/pdf_icon.jpg") %>
             <% end %>
	   <% elsif (current_user.groups.include?("community") && !embargo.nil?) || (current_user.groups.include?("public")) %>
	     <%#= link_to_document document, :label => image_tag("blacklight/pdf_icon.jpg"), :counter => counter %>
             <%#= image_tag("blacklight/pdf_icon.jpg") %>
	   <% end %>

	 <% elsif (current_user.nil?)%>
	   <% if (on_campus && embargo.nil?) %>
	     <%= link_to link, :title => "PDF_Link", :target => "_blank" do %>
		<%= image_tag("blacklight/pdf_icon.jpg") %>
	     <% end %>
	   <% elsif (on_campus && !embargo.nil?) || (!on_campus) %>
	     <%#= link_to_document document, :label => image_tag("blacklight/pdf_icon.jpg"), :counter => counter %>
             <%#= image_tag("blacklight/pdf_icon.jpg") %>
	   <% end %>
	
	 <% end %>

      </div>

app/views/catalog/_email_form.html.erb
<%= form_tag url_for(:controller => "catalog", :action => "email"), :id => 'email_form', :class => "form-horizontal ajax_form", :method => :post do %>
<%#= form_tag url_for(:controller => "catalog", :action => "ucsb_email"), :id => 'email_form', :class => "form-horizontal ajax_form", :method => :post do %>

  <div class="modal-body">
    <%= render :partial=>'/flash_msg' %>
    <div class="control-group">
      <label class="control-label" for="to">
        <%= t('blacklight.email.form.to') %>
      </label>
      <div class="controls">

        <%= text_field_tag :to, params[:to] %><br/>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="message">
        <%= t('blacklight.email.form.message') %>
      </label>
      <div class="controls">
      <%= text_area_tag :message, params[:message] %>
       </div>
    </div>

    <% @documents.each do |doc| %>
      <%=hidden_field_tag "id[]", doc.get(:id)%>
    <% end %>
    <%- if params[:sort] -%>
      <%= hidden_field_tag "sort", params[:sort] %>
    <%- end -%>
    <%- if params[:per_page] -%>
      <%= hidden_field_tag "per_page", params[:per_page] %>
    <%- end -%>
  </div>
  <div class="modal-footer">
  <button type="submit" class="btn btn-primary"> <%= t('blacklight.sms.form.submit') %></button>
  </div>
<% end %>

app/views/catalog/_etds_collections.html.erb
<% url = APP_CONFIG['rails_url'] %>
<div id="etds_collections_body">

  <p class="collections_header">Browse By Collection</p>
<!--div id="etds_collections_container"-->

  <div id="etds_view_link">
    <p>Current collections are listed below. Click on the image or link below to see the items in each collection.</p>
  </div>

  <div id="etds_collections_sidebar_image">
      <!-- insert your sidebar items here -->
      <!--img alt="body_image" src="blacklight/index_body_image.jpg", width="400"></img-->
      <%#= image_tag("blacklight/index_body_image.jpg", width: '400') %>
      <a  href="/catalog?f%5Bobject_type_sim%5D%5B%5D=Thesis+or+dissertation"><%= image_tag("blacklight/ETD_Collection_Crop_150x150.jpg") %></a>
      <!--<p>Photo by Patricia Marroquin</p>-->
  </div>
  <br/>
<!--/div>

<div id="etds_collections_container_2"-->
  <div id="etds_collections_content">
    <strong><a href="/catalog?f%5Bobject_type_sim%5D%5B%5D=Thesis+or+dissertation">Electronic Theses and Dissertations</a></strong>
    <!--Currently, more than  <%= @count %> 850 theses and dissertations from 2011-2013 can -->
    <p>
In partnership with the Graduate Division, the UCSB Library is making available theses and dissertations produced by UCSB students. Currently included in ADRL are theses and dissertations that were originally filed electronically, starting in 2011. In future phases of ADRL, all theses and dissertations created by UCSB students will be digitized and made available    
<br /><br />

  </div>
<!--/div-->
</div>


<%#= render 'search_sidebar' %>

app/views/catalog/_footer.html.erb
     
      <% # header bar for doc items in index view -%>
      <div class="footer">
        
        <%- # main title container for doc partial view -%>
         <h5 class="index_title">
	  Test Footer
        </h5>

      </div>
      

app/views/catalog/_home_text.html.erb
<% url = APP_CONFIG['rails_url'] %>

<div> 

<h4><%= t('blacklight.welcome') %></h4>
<%- if (!(current_user.nil?)) && ((current_user.groups.include?("admin")) || (current_user.groups.include?("staff"))) %>
  <p> <%= link_to 'Batch Ingest', (url + 'ingest/ingest') %></p> <br />
<%- end %>

<p>&nbsp;</p>
<!--p>To modify this text to your specifications, copy this file located in the blacklight plugin directory:<br/>
&nbsp;&nbsp;&nbsp;<%= Blacklight.root %>/app/views/catalog/_home_text.html.erb</p>
<p>to your top level rails app:<br/>
&nbsp;&nbsp;&nbsp;<%= Rails.root %>/app/views/catalog/_home_text.html.erb</p>
<p>Note that you will need to create the 'catalog' directory under views.</p-->
<% #Creates a bit space in the page -%>

</div>

app/views/catalog/_previous_next_doc.html.erb
<% #Using the Bootstrap Pagination class  -%>
<% if @previous_document || @next_document %>
	<div class="well" id="previousNextDocument">
    <%= link_to_previous_document @previous_document %> |

    <%= item_page_entry_info %> |

    <%= link_to_next_document @next_document %>

<div class="pull-right">
      <%= link_back_to_catalog %>
      |
      <%=link_to "#{t('blacklight.search.start_over')}", catalog_index_path, :id=>"startOverLink" %>
  </div>
	</div>
<% end %>

app/views/catalog/_search_form.html.erb
  <%= form_tag search_action_url, :method => :get, :class => 'search-query-form form-inline clearfix' do %>
    <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>

    <% unless search_fields.empty? %>
      <div class="pull-left">
        <label for="search_field" class="hide-text"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field input-small") %>
        <span class="hide-text"><%= t('blacklight.search.form.search_field.post_label') %></span>
      </div>
      <% end %>
       <div class="input-append pull-left">
        <label for="q" class="hide-text"><%= t('blacklight.search.form.q') %></label>
         <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q", :id => "q", :autofocus => should_autofocus_on_search_box? %>

        <button type="submit" class="btn btn-primary search-btn" id="search">
          <span class="submit-search-text"></span>
          <i class="icon-search icon-white"></i>
        </button>
       </div>

  <% end %>

<!-- Advanced search link -->
<!-- <%#= link_to_unless(current_user.nil?, 'Advanced Search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search") %> -->

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

  #Added Bootstrap class well and 'hidden-phone' for the tools-bar 
-%>
  <ul class="nav nav-list">
      <li class="nav-header"><%= t('blacklight.tools.title') %></li>
      <li>
        <%= render_show_doc_actions @document %>
      </li>
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :class => 'lightboxLink'} %>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document)  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <%= link_to t('blacklight.tools.email'), email_catalog_path(:id => @document), {:id => 'emailLink', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :class => 'lightboxLink'} %>
      </li>
    <% end %>
  </ul>

app/views/catalog/_splash_search_form.html.erb
  <%= form_tag search_action_url, :method => :get, :class => 'search-query-form form-inline clearfix' do %>
    <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>

    <% unless search_fields.empty? %>
      <div class="pull-left splash-search-select">
        <label for="search_field" class="hide-text"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field input-splash-dropdown") %>
        <span class="hide-text"><%= t('blacklight.search.form.search_field.post_label') %></span>
      </div>
      <% end %>
       <div class="input-append pull-left splash-search-query">
        <label for="q" class="hide-text"><%= t('blacklight.search.form.q') %></label>
         <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q search-splash-q", :id => "q", :autofocus => should_autofocus_on_search_box? %>

        <button type="submit" class="btn btn-primary search-btn search-splash-button" id="search">
          <span class="submit-search-text"></span>
          <i class="icon-search icon-white"></i>
        </button>
       </div>

  <% end %>

<!-- Advanced search link -->
<!-- <%#= link_to_unless(current_user.nil?, 'Advanced Search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search") %> -->

app/views/catalog/index.html.erb
<!--div id="sidebar" class="span3">
 <%= render 'search_sidebar' %>
</div-->

<!--div id="content" class="span9"-->

<% unless has_search_parameters? %>
  <div id="content" class="span9">
    <%# if there are no input/search related params, display the "home" partial -%>
    <%#= render 'home' %>
    <%= render 'etds_collections' %>
  </div>
  <!-- commented out facets search bar -->
  <!--<div id="sidebar" class="span3">
    <%= render 'search_sidebar' %>
  </div>-->

<% else %>

  <div id="sidebar" class="span3">
    <%= render 'search_sidebar' %>
  </div>

  <div id="content" class="span9">
      <h2 class="hide-text top-content-title"><%= t('blacklight.search.search_results_header') %></h2>

      <% @page_title = t('blacklight.search.title', :application_name => application_name) %>


      <% extra_head_content << render_opensearch_response_metadata.html_safe %>

	    <%= render 'did_you_mean' %>

      <%= render 'constraints' %>

      <%= render 'sort_and_per_page' %>

      <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>

      <%- if response_has_no_search_results? %>
        <%= render "zero_results" %>
      <%- elsif render_grouped_response? %>
        <%= render_grouped_document_index %>
      <%- else %>
        <%= render_document_index %>
      <%- end %>

	    <%= render 'results_pagination' %>
  </div>
<% end %>

<!--/div-->